import type { SprintBoardData } from "./types";

export const sprintBoardMockData: SprintBoardData = {
  sprint: {
    id: "sprint-42",
    name: "Sprint 42: Data Pipeline Opt.",
    projectPath: ["Projects", "Core Platform", "Active Sprint"],
    startDateLabel: "Oct 12",
    endDateLabel: "Oct 26",
    daysRemaining: 3,
    storyPointGoal: 124,
  },
  members: [
    { id: "m-ayu", name: "Ayu S", avatar: "AS", color: "#4f46e5" },
    { id: "m-bima", name: "Bima P", avatar: "BP", color: "#0891b2" },
    { id: "m-rani", name: "Rani M", avatar: "RM", color: "#f97316" },
    { id: "m-jordan", name: "Jordan D", avatar: "JD", color: "#2563eb" },
    { id: "m-luna", name: "Luna K", avatar: "LK", color: "#10b981" },
  ],
  stats: [
    { id: "total", label: "Total Points", value: "124" },
    { id: "completed", label: "Completed", value: "86", tone: "success" },
    { id: "remaining", label: "Remaining", value: "38", tone: "warning" },
  ],
  tasks: [
    {
      id: "ENG-402",
      title: "Refactor event ingestion pipeline",
      status: "todo",
      priority: "medium",
      dueDate: "2026-10-22",
      storyPoints: 3,
      tags: ["Backend"],
      assigneeIds: ["m-ayu"],
    },
    {
      id: "ENG-415",
      title: "Update dependency versions for Q4",
      status: "todo",
      priority: "low",
      dueDate: "2026-10-24",
      storyPoints: 2,
      tags: ["Chore"],
      assigneeIds: ["m-rani"],
    },
    {
      id: "ENG-398",
      title: "Implement Redis caching for API endpoints",
      status: "in_progress",
      priority: "high",
      dueDate: "2026-10-21",
      storyPoints: 5,
      tags: ["Backend"],
      assigneeIds: ["m-bima", "m-jordan"],
    },
    {
      id: "ENG-390",
      title: "Migrate user auth database to Postgres 15",
      status: "review",
      priority: "critical",
      dueDate: "2026-10-19",
      storyPoints: 8,
      tags: ["Database"],
      assigneeIds: ["m-rani", "m-luna"],
    },
    {
      id: "ENG-411",
      title: "Finalize build pipeline stability fixes",
      status: "done",
      priority: "medium",
      dueDate: "2026-10-18",
      storyPoints: 3,
      tags: ["DevOps"],
      assigneeIds: ["m-jordan"],
    },
    {
      id: "ENG-406",
      title: "Design board filter interaction states",
      status: "done",
      priority: "low",
      dueDate: "2026-10-16",
      storyPoints: 2,
      tags: ["Design"],
      assigneeIds: ["m-luna"],
    },
  ],
  sidebarItems: [
    { label: "Dashboard", href: "/dashboard", icon: "dashboard" },
    { label: "Project", href: "/projects", icon: "project" },
    { label: "Sprint", href: "/sprints", icon: "sprint", active: true },
    { label: "Tasks", href: "/tasks", icon: "tasks" },
    { label: "Analytics", href: "/analytics", icon: "analytics" },
    { label: "AI Assistant", href: "/ai", icon: "ai" },
    { label: "Team", href: "/team", icon: "team" },
    { label: "Settings", href: "/settings", icon: "settings" },
  ],
};

