"""Initial schema

Revision ID: 8c257a2635b9
Revises: 
Create Date: 2026-05-12 17:23:37.229064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c257a2635b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('division_id')
    )
    op.create_index(op.f('ix_divisions_division_id'), 'divisions', ['division_id'], unique=False)
    op.create_index(op.f('ix_divisions_name'), 'divisions', ['name'], unique=True)
    op.create_table('global_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_run', sa.String(length=50), nullable=True),
    sa.Column('next_run', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_global_jobs_job_id'), 'global_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_global_jobs_job_name'), 'global_jobs', ['job_name'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_permission_id'), 'permissions', ['permission_id'], unique=False)
    op.create_table('project_workspaces',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_index(op.f('ix_project_workspaces_name'), 'project_workspaces', ['name'], unique=False)
    op.create_index(op.f('ix_project_workspaces_workspace_id'), 'project_workspaces', ['workspace_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('audit_system_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_system_logs_audit_id'), 'audit_system_logs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_system_logs_changed_by'), 'audit_system_logs', ['changed_by'], unique=False)
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.division_id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_categories_division_id'), 'categories', ['division_id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('repository_token', sa.String(length=500), nullable=True),
    sa.Column('repository_type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['project_workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_permission_id'), 'role_permissions', ['role_permission_id'], unique=False)
    op.create_table('user_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_user_logs_log_id'), 'user_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_user_logs_user_id'), 'user_logs', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_role_id'), 'user_roles', ['user_role_id'], unique=False)
    op.create_table('workers',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.division_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_workers_division_id'), 'workers', ['division_id'], unique=False)
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=True)
    op.create_index(op.f('ix_workers_user_id'), 'workers', ['user_id'], unique=True)
    op.create_index(op.f('ix_workers_worker_id'), 'workers', ['worker_id'], unique=False)
    op.create_table('commit_change_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('commits_fetched', sa.Integer(), nullable=True),
    sa.Column('commits_failed', sa.Integer(), nullable=True),
    sa.Column('sync_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_date', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_commit_change_logs_log_id'), 'commit_change_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_commit_change_logs_project_id'), 'commit_change_logs', ['project_id'], unique=False)
    op.create_table('project_commit_tracking',
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=100), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=False),
    sa.Column('commit_date', sa.String(length=50), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('file_list', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('commit_id')
    )
    op.create_index(op.f('ix_project_commit_tracking_author_email'), 'project_commit_tracking', ['author_email'], unique=False)
    op.create_index(op.f('ix_project_commit_tracking_commit_hash'), 'project_commit_tracking', ['commit_hash'], unique=True)
    op.create_index(op.f('ix_project_commit_tracking_commit_id'), 'project_commit_tracking', ['commit_id'], unique=False)
    op.create_index(op.f('ix_project_commit_tracking_project_id'), 'project_commit_tracking', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_commit_tracking_worker_id'), 'project_commit_tracking', ['worker_id'], unique=False)
    op.create_table('project_details',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_project_details_detail_id'), 'project_details', ['detail_id'], unique=False)
    op.create_index(op.f('ix_project_details_project_id'), 'project_details', ['project_id'], unique=False)
    op.create_table('project_summaries',
    sa.Column('project_summary_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('total_effort', sa.Float(), nullable=True),
    sa.Column('actual_duration_days', sa.Integer(), nullable=True),
    sa.Column('key_achievements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('project_summary_id')
    )
    op.create_index(op.f('ix_project_summaries_project_id'), 'project_summaries', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_summaries_project_summary_id'), 'project_summaries', ['project_summary_id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.String(length=50), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['workers.worker_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_project_tasks_assigned_to'), 'project_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_task_id'), 'project_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_title'), 'project_tasks', ['title'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('capacity_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_category_id'), 'teams', ['category_id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_team_id'), 'teams', ['team_id'], unique=False)
    op.create_table('worker_kpi',
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('calculated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('kpi_id')
    )
    op.create_index(op.f('ix_worker_kpi_kpi_id'), 'worker_kpi', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_worker_kpi_project_id'), 'worker_kpi', ['project_id'], unique=False)
    op.create_index(op.f('ix_worker_kpi_worker_id'), 'worker_kpi', ['worker_id'], unique=False)
    op.create_table('worker_kpi_summaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_projects', sa.Integer(), nullable=False),
    sa.Column('peer_percentile', sa.Integer(), nullable=True),
    sa.Column('trend_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_worker_kpi_summaries_summary_id'), 'worker_kpi_summaries', ['summary_id'], unique=False)
    op.create_index(op.f('ix_worker_kpi_summaries_worker_id'), 'worker_kpi_summaries', ['worker_id'], unique=False)
    op.create_table('worker_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_contact', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_worker_profiles_profile_id'), 'worker_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_worker_profiles_worker_id'), 'worker_profiles', ['worker_id'], unique=True)
    op.create_table('project_detail_docs',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('doc_url', sa.String(length=500), nullable=False),
    sa.Column('doc_name', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['project_details.detail_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_project_detail_docs_detail_id'), 'project_detail_docs', ['detail_id'], unique=False)
    op.create_index(op.f('ix_project_detail_docs_doc_id'), 'project_detail_docs', ['doc_id'], unique=False)
    op.create_table('project_detail_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['project_details.detail_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_project_detail_images_detail_id'), 'project_detail_images', ['detail_id'], unique=False)
    op.create_index(op.f('ix_project_detail_images_image_id'), 'project_detail_images', ['image_id'], unique=False)
    op.create_table('project_task_comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_project_task_comments_comment_id'), 'project_task_comments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_project_task_comments_task_id'), 'project_task_comments', ['task_id'], unique=False)
    op.create_table('project_task_histories',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_project_task_histories_history_id'), 'project_task_histories', ['history_id'], unique=False)
    op.create_index(op.f('ix_project_task_histories_task_id'), 'project_task_histories', ['task_id'], unique=False)
    op.create_table('project_task_summaries',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('total_effort', sa.Float(), nullable=True),
    sa.Column('completion_date', sa.String(length=50), nullable=True),
    sa.Column('contributors', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_project_task_summaries_summary_id'), 'project_task_summaries', ['summary_id'], unique=False)
    op.create_index(op.f('ix_project_task_summaries_task_id'), 'project_task_summaries', ['task_id'], unique=False)
    op.create_table('project_task_workloads',
    sa.Column('workload_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.String(length=50), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.task_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('workload_id')
    )
    op.create_index(op.f('ix_project_task_workloads_task_id'), 'project_task_workloads', ['task_id'], unique=False)
    op.create_index(op.f('ix_project_task_workloads_worker_id'), 'project_task_workloads', ['worker_id'], unique=False)
    op.create_index(op.f('ix_project_task_workloads_workload_id'), 'project_task_workloads', ['workload_id'], unique=False)
    op.create_table('project_teams',
    sa.Column('project_team_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('project_team_id')
    )
    op.create_index(op.f('ix_project_teams_project_id'), 'project_teams', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_teams_project_team_id'), 'project_teams', ['project_team_id'], unique=False)
    op.create_index(op.f('ix_project_teams_team_id'), 'project_teams', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('team_member_id')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_member_id'), 'team_members', ['team_member_id'], unique=False)
    op.create_index(op.f('ix_team_members_worker_id'), 'team_members', ['worker_id'], unique=False)
    op.create_table('team_workspaces',
    sa.Column('team_workspace_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['project_workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('team_workspace_id')
    )
    op.create_index(op.f('ix_team_workspaces_team_id'), 'team_workspaces', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_workspaces_team_workspace_id'), 'team_workspaces', ['team_workspace_id'], unique=False)
    op.create_index(op.f('ix_team_workspaces_workspace_id'), 'team_workspaces', ['workspace_id'], unique=False)
    op.create_table('project_team_members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('project_team_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('allocation_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_team_id'], ['project_teams.project_team_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_project_team_members_member_id'), 'project_team_members', ['member_id'], unique=False)
    op.create_index(op.f('ix_project_team_members_project_team_id'), 'project_team_members', ['project_team_id'], unique=False)
    op.create_index(op.f('ix_project_team_members_worker_id'), 'project_team_members', ['worker_id'], unique=False)
    op.create_table('project_team_selections',
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('project_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('selection_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_team_id'], ['project_teams.project_team_id'], ),
    sa.PrimaryKeyConstraint('selection_id')
    )
    op.create_index(op.f('ix_project_team_selections_project_team_id'), 'project_team_selections', ['project_team_id'], unique=False)
    op.create_index(op.f('ix_project_team_selections_selection_id'), 'project_team_selections', ['selection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_team_selections_selection_id'), table_name='project_team_selections')
    op.drop_index(op.f('ix_project_team_selections_project_team_id'), table_name='project_team_selections')
    op.drop_table('project_team_selections')
    op.drop_index(op.f('ix_project_team_members_worker_id'), table_name='project_team_members')
    op.drop_index(op.f('ix_project_team_members_project_team_id'), table_name='project_team_members')
    op.drop_index(op.f('ix_project_team_members_member_id'), table_name='project_team_members')
    op.drop_table('project_team_members')
    op.drop_index(op.f('ix_team_workspaces_workspace_id'), table_name='team_workspaces')
    op.drop_index(op.f('ix_team_workspaces_team_workspace_id'), table_name='team_workspaces')
    op.drop_index(op.f('ix_team_workspaces_team_id'), table_name='team_workspaces')
    op.drop_table('team_workspaces')
    op.drop_index(op.f('ix_team_members_worker_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_member_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_project_teams_team_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_project_team_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_project_id'), table_name='project_teams')
    op.drop_table('project_teams')
    op.drop_index(op.f('ix_project_task_workloads_workload_id'), table_name='project_task_workloads')
    op.drop_index(op.f('ix_project_task_workloads_worker_id'), table_name='project_task_workloads')
    op.drop_index(op.f('ix_project_task_workloads_task_id'), table_name='project_task_workloads')
    op.drop_table('project_task_workloads')
    op.drop_index(op.f('ix_project_task_summaries_task_id'), table_name='project_task_summaries')
    op.drop_index(op.f('ix_project_task_summaries_summary_id'), table_name='project_task_summaries')
    op.drop_table('project_task_summaries')
    op.drop_index(op.f('ix_project_task_histories_task_id'), table_name='project_task_histories')
    op.drop_index(op.f('ix_project_task_histories_history_id'), table_name='project_task_histories')
    op.drop_table('project_task_histories')
    op.drop_index(op.f('ix_project_task_comments_task_id'), table_name='project_task_comments')
    op.drop_index(op.f('ix_project_task_comments_comment_id'), table_name='project_task_comments')
    op.drop_table('project_task_comments')
    op.drop_index(op.f('ix_project_detail_images_image_id'), table_name='project_detail_images')
    op.drop_index(op.f('ix_project_detail_images_detail_id'), table_name='project_detail_images')
    op.drop_table('project_detail_images')
    op.drop_index(op.f('ix_project_detail_docs_doc_id'), table_name='project_detail_docs')
    op.drop_index(op.f('ix_project_detail_docs_detail_id'), table_name='project_detail_docs')
    op.drop_table('project_detail_docs')
    op.drop_index(op.f('ix_worker_profiles_worker_id'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_profile_id'), table_name='worker_profiles')
    op.drop_table('worker_profiles')
    op.drop_index(op.f('ix_worker_kpi_summaries_worker_id'), table_name='worker_kpi_summaries')
    op.drop_index(op.f('ix_worker_kpi_summaries_summary_id'), table_name='worker_kpi_summaries')
    op.drop_table('worker_kpi_summaries')
    op.drop_index(op.f('ix_worker_kpi_worker_id'), table_name='worker_kpi')
    op.drop_index(op.f('ix_worker_kpi_project_id'), table_name='worker_kpi')
    op.drop_index(op.f('ix_worker_kpi_kpi_id'), table_name='worker_kpi')
    op.drop_table('worker_kpi')
    op.drop_index(op.f('ix_teams_team_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_category_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_project_tasks_title'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_task_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_assigned_to'), table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_project_summaries_project_summary_id'), table_name='project_summaries')
    op.drop_index(op.f('ix_project_summaries_project_id'), table_name='project_summaries')
    op.drop_table('project_summaries')
    op.drop_index(op.f('ix_project_details_project_id'), table_name='project_details')
    op.drop_index(op.f('ix_project_details_detail_id'), table_name='project_details')
    op.drop_table('project_details')
    op.drop_index(op.f('ix_project_commit_tracking_worker_id'), table_name='project_commit_tracking')
    op.drop_index(op.f('ix_project_commit_tracking_project_id'), table_name='project_commit_tracking')
    op.drop_index(op.f('ix_project_commit_tracking_commit_id'), table_name='project_commit_tracking')
    op.drop_index(op.f('ix_project_commit_tracking_commit_hash'), table_name='project_commit_tracking')
    op.drop_index(op.f('ix_project_commit_tracking_author_email'), table_name='project_commit_tracking')
    op.drop_table('project_commit_tracking')
    op.drop_index(op.f('ix_commit_change_logs_project_id'), table_name='commit_change_logs')
    op.drop_index(op.f('ix_commit_change_logs_log_id'), table_name='commit_change_logs')
    op.drop_table('commit_change_logs')
    op.drop_index(op.f('ix_workers_worker_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_user_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.drop_index(op.f('ix_workers_division_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_user_roles_user_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_logs_user_id'), table_name='user_logs')
    op.drop_index(op.f('ix_user_logs_log_id'), table_name='user_logs')
    op.drop_table('user_logs')
    op.drop_index(op.f('ix_role_permissions_role_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_division_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_system_logs_changed_by'), table_name='audit_system_logs')
    op.drop_index(op.f('ix_audit_system_logs_audit_id'), table_name='audit_system_logs')
    op.drop_table('audit_system_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_project_workspaces_workspace_id'), table_name='project_workspaces')
    op.drop_index(op.f('ix_project_workspaces_name'), table_name='project_workspaces')
    op.drop_table('project_workspaces')
    op.drop_index(op.f('ix_permissions_permission_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_global_jobs_job_name'), table_name='global_jobs')
    op.drop_index(op.f('ix_global_jobs_job_id'), table_name='global_jobs')
    op.drop_table('global_jobs')
    op.drop_index(op.f('ix_divisions_name'), table_name='divisions')
    op.drop_index(op.f('ix_divisions_division_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###
